language: node_js
node_js:
  - 0.10
  - 0.11

after_script:
  - npm run coveralls

notifications:
  email:
    recipients:
      - isv.damocles@gmail.com
    on_success: change
    on_failure: change
